export const VALID_USER = 'VALID_USER'
export const INVALID_USER = 'INVALID_USER'
export const SEND_SUCCESSFUL = 'SEND_SUCCESSFUL'
export const SEND_FAILED = 'SEND_FAILED'
export const RETRIEVE_EMAIL_SUCCESSFUL = 'RETRIEVE_EMAIL_SUCCESSFUL'
export const RETRIEVE_EMAIL_FAILED = 'RETRIEVE_EMAIL_FAILED'

